version: '0.3.0.{build}'

build: false
environment:
  matrix:
  - PHP_VERSION: 7.0
    PHP_TYPE: "Win32"
  - PHP_VERSION: 7.0
    PHP_TYPE: "nts-Win32"
  - PHP_VERSION: 5.6
    PHP_TYPE: "Win32"
  - PHP_VERSION: 5.6
    PHP_TYPE: "nts-Win32"
  PHP_SDK: c:\projects\php-sdk
  PHP_DEVPACK: c:\projects\php-devpack
  PHP_DEPS: c:\projects\deps
  NO_INTERACTION: 1
  SSL_VER: 1_0_2j

matrix:
    allow_failures:
        - platform: x64

clone_folder: c:\projects\extension

os: Windows Server 2012 R2

platform:
    - x86
    - x64

init:
    - SET PATH=C:\Program Files (x86)\MSBuild\%PHP_VC%.0\Bin;%PATH%
    - SET PATH=c:\php;c:\projects\php-devpack;%PATH%
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
  - echo Setting PHP version...
  - ps: >-
      If ($env:PHP_VERSION -Match "5.6") {
        Start-FileDownload 'http://windows.php.net/downloads/releases/sha1sum.txt'
        $env:PHP_VERSION=type sha1sum.txt | where { $_ -match "php-(5\.6\.\d+)-src" } | foreach { $matches[1] }
        $env:version='{build}-$(PHP_VERSION)'
        $env:PHP_VC=11
      } elseif ($env:PHP_VERSION -Match "5.5") {
        Start-FileDownload 'http://windows.php.net/downloads/releases/sha1sum.txt'
        $env:PHP_VERSION=type sha1sum.txt | where { $_ -match "php-(5\.5\.\d+)-src" } | foreach { $matches[1] }
        $env:version='{build}-$(PHP_VERSION)'
        $env:PHP_VC=11
      } elseif ($env:PHP_VERSION -Match "7.0") {
        Start-FileDownload 'http://windows.php.net/downloads/releases/sha1sum.txt'
        $env:PHP_VERSION=type sha1sum.txt | where { $_ -match "php-(7\.0\.\d+)-src" } | foreach { $matches[1] }
        $env:version='{build}-$(PHP_VERSION)'
        $env:PHP_VC=14
      } Else {
        $env:version='{build}-$(PHP_VERSION)'
      }
      If ($env:PLATFORM -Match "x86") {
        If ($env:PHP_TYPE -Match "nts-Win32") {
          $env:RELEASE_FOLDER="Release"
        } Else {
          $env:RELEASE_FOLDER="Release_TS"
        }
      } else {
        If ($env:PHP_TYPE -Match "nts-Win32") {
          $env:RELEASE_FOLDER="x64\Release"
        } Else {
          $env:RELEASE_FOLDER="x64\Release_TS"
        }
      }
      If ($env:PHP_VC -eq '11') {
        $env:VSCOMNTOOLS=$env:VS110COMNTOOLS
      } elseif ($env:PHP_VC -eq '14') {
        $env:VSCOMNTOOLS=$env:VS140COMNTOOLS
      }
      If ($env:PLATFORM -eq 'x64') {
        $env:ARCH='x86_amd64'
      } Else {
        $env:ARCH='x86'
      }
  - echo Initializing Build with %PHP_VC% for %ARCH%...
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo Preparing extension build...
  - echo Downloading PHP source code [%PHP_VERSION%]
  - echo http://windows.php.net/downloads/releases/php-%PHP_VERSION%-%PHP_TYPE%-VC%PHP_VC%-%PLATFORM%.zip
  - set PHP_SOURCE_FILE="http://windows.php.net/downloads/releases/php-%PHP_VERSION%-%PHP_TYPE%-VC%PHP_VC%-%PLATFORM%.zip"
  - appveyor DownloadFile %PHP_SOURCE_FILE% -FileName %APPVEYOR_BUILD_FOLDER%\..\php.zip
  - cd ..
  - 'mkdir php && mv php.zip php\php.zip && cd php'
  - 7z.exe x php.zip | FIND /V "ing  "
  - cd ..
  - echo Downloading PHP-SDK
  - mkdir php-sdk && cd php-sdk
  - appveyor DownloadFile http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip -FileName %APPVEYOR_BUILD_FOLDER%\..\php-sdk.zip
  - '7z.exe x ..\php-sdk.zip | FIND /V "ing  "'
  - cd ..
  - echo Downloading PHP-Devel-Pack
  - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/releases/php-devel-pack-' + ${env:PHP_VERSION} + '-' + ${env:PHP_TYPE} + '-VC' + ${env:PHP_VC} + '-' + ${env:PLATFORM} + '.zip', ${env:APPVEYOR_BUILD_FOLDER} + '\..\php-dev.zip')
  - appveyor DownloadFile http://windows.php.net/downloads/releases/php-devel-pack-%PHP_VERSION%-%PHP_TYPE%-VC%PHP_VC%-%PLATFORM%.zip
  - 7z.exe x php-dev.zip | FIND /V "ing  "
  - mv php-%PHP_VERSION%-devel-VC%PHP_VC%-%PLATFORM% php-devpack
  - echo Downloading Mosquitto deps
  - 'mkdir deps && cd deps'
  - appveyor DownloadFile http://slproweb.com/download/Win32OpenSSL-%SSL_VER%.exe
  - Win32OpenSSL-%SSL_VER%.exe /silent /verysilent /sp- /suppressmsgboxes
  - curl -fsSO ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip
  - 7z -y x pthreads-w32-2-9-1-release.zip -oC:\pthreads\
  - ps: Start-FileDownload -FileName mosquitto-install.exe "http://www.eclipse.org/downloads/download.php?file=/mosquitto/binary/win32/mosquitto-1.4.10-install-win32.exe&r=1"
  - dir
    echo Setting up Mosquitto
  - mosquitto-install.exe /S /D=C:\mosquitto
  - echo Setting up PHP [%PHP_VERSION%]
  - '%PHP_SDK%\bin\phpsdk_setvars'
  - 'cd %APPVEYOR_BUILD_FOLDER%\..\php'
  - 'echo extension_dir=%APPVEYOR_BUILD_FOLDER%\..\php\ext > php.ini'
  - 'set PATH=%cd%;%PATH%'

test_script:
    - cd c:\projects\extension
    - '"C:\\Program Files (x86)\\Microsoft Visual Studio %PHP_VC%.0\\VC\\vcvarsall.bat" %ARCH%'
    - Setlocal EnableDelayedExpansion
    - phpize
    - configure --with-mosquitto=shared --with-php-build=c:\projects\deps
    - nmake 2> compile-errors.log 1>compile.log
    - nmake test

on_failure:
  - 'dir'
  - 'type compile-errors.log'
  - 'type compile.log'
  - 'type Makefile'

artifacts:
  - path: '$(RELEASE_FOLDER)\php_mosquitto.dll'

